# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sname', models.CharField(max_length=32)),
                ('spwd', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
