# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0002_auto_20210120_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_test01.Student')),
                ('major', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Card',
            },
        ),
    ]
