# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0003_card_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Class',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'C_Class',
            },
        ),
        migrations.CreateModel(
            name='C_Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('c_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_test01.C_Class')),
            ],
            options={
                'db_table': 'C_Student',
            },
        ),
    ]
