# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0004_c_class_c_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'sys_course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_no', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=16)),
                ('mid_cou_no', models.ManyToManyField(to='project_test01.Course')),
            ],
            options={
                'db_table': 'sys_teacher',
            },
        ),
        migrations.AlterField(
            model_name='c_student',
            name='c_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='project_test01.C_Class'),
        ),
    ]
