# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0005_auto_20210124_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SClass',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'S_class',
            },
        ),
        migrations.CreateModel(
            name='SCourse',
            fields=[
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'S_course',
            },
        ),
        migrations.CreateModel(
            name='SStudent',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('s_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_test01.SClass')),
                ('s_cour', models.ManyToManyField(to='project_test01.SCourse')),
            ],
            options={
                'db_table': 'S_student',
            },
        ),
    ]
