# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-31 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0006_sclass_scourse_sstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=31)),
                ('is_deleter', models.BinaryField(default=False)),
            ],
            options={
                'db_table': 'T_student',
            },
        ),
    ]
