# Generated by Django 3.1.7 on 2021-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_test01', '0008_auto_20210131_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='imgs')),
            ],
            options={
                'db_table': 'File_Student',
            },
        ),

    ]
