from django.conf.urls import url
from . import views
urlpatterns = [
       url(r'^test/$', views.test),
       url(r'^login/$', views.login),
       url(r'^login/submit/$', views.login_operation),
       url(r'^register_index/$', views.register_index),
       url(r'^register/$', views.register),
       url(r'^user/query/$', views.user_query),
       url(r'^film/$', views.film_pager),
       url(r'^film_native/$', views.native_pager_film),
       url(r'pro_register/$', views.student_pro_register),
       url(r'pro_register/showall/$', views.student_pro_register_showall),
       url(r'pro_register/getstu/detail/$', views.getstu_detail),
       url(r'^urls1/(\d{2})$', views.test_url),
       url(r'^urls2/(\d{4})/(\d{2})/(\d{2})', views.test_url2),
       url(r'^urls3/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})', views.test_url3),
       url(r'^reverse_urls_index/', views.reverse_url_index),
       url(r'^reverse_urls/(\d{2})', views.reverse_url, name='q'),
       url(r'^reverse_redirect_urls/', views.reverse_redirect_urls),
       url(r'^include/', views.inculde, name='q1'),
       url(r'^$', views.index),
       url(r'^test_http_request/$', views.test_http_request),
       url(r'^upload/$', views.file_upload),
       url(r'^upload_db/$', views.file_upload_db),
       url(r'^show_all_photo/$', views.show_all_photo),
       url(r'^photo_download/$', views.photo_download),
       url(r'^custom/$', views.error_page_custom),
       url(r'^redirect_befor/$', views.redirect_befor),
       url(r'^redirect_after/$', views.redirect_after),
       url(r'^cookie/$', views.cookie),
       url(r'^get_cookie/$', views.get_cookie),
       url(r'^set_cookie_login/$', views.set_cookie_login),
       url(r'^session/$', views.session),
       url(r'^get_session/$', views.get_session),
       url(r'^set_session_login/$', views.set_session_login),
       url(r'^usercenter/$', views.usercenter),
       url(r'^class_views/$', views.Class_Views.as_view()),
       url(r'^show_pic/$', views.ShowPic.as_view()),
       url(r'^static_views/(.*)$', views.StaticViews.as_view()),
       url(r'^templates_views1/$', views.templates_views1),
       url(r'^templates_lable/$', views.templates_lable),
       url(r'^test_filters/$', views.TestFilters.as_view()),
       url(r'^custom_filters/$', views.CustomFilters.as_view()),
       url(r'^context_prosessors/$', views.ContextProsessors.as_view()),
       url(r'^inherit_template/$', views.InheritTemplate.as_view()),
       url(r'^test_forms_class/$', views.TestFormsClass.as_view()),
       url(r'^test_models_forms_class/$', views.TestModelFormsClass.as_view()),
       url(r'^js_templates_check/$', views.JsTemplatesCheck.as_view()),
       url(r'^test_ajax/$', views.TestAjax.as_view()),
       url(r'^get_ajax_data/$', views.get_ajax_data),
       url(r'^post_ajax_data/$', views.post_ajax_data),
       url(r'^ajax_login_check/$', views.AjaxLoginCheck.as_view()),
       url(r'^only_user/$', views.only_user),
       url(r'^cache/$', views.test_cache),
       url(r'^cache_redis/$', views.cache_redis),

]

