# Generated by Django 3.1.7 on 2021-04-17 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='cname',
            field=models.CharField(max_length=30, unique=True, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
