# Generated by Django 3.1.7 on 2021-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210417_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='data_time',
            field=models.DateField(auto_now_add=True, default='2021-04-17'),
            preserve_default=False,
        ),
    ]
