# Generated by Django 3.1.7 on 2021-04-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcontent_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2021-04-17'),
            preserve_default=False,
        ),
    ]
