# Generated by Django 3.1.7 on 2021-04-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcontent_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='data',
        ),
    ]
